-- Create providers table
create table public.providers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_name text,
  email text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.providers enable row level security;

-- Create policy to allow all access (for development simplicity - refine in production)
create policy "Enable all access for all users" on public.providers
for all using (true) with check (true);
