-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  price numeric(10, 2) not null,
  stock integer not null default 0,
  provider_id bigint references public.providers(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.products enable row level security;

-- Create policy to allow all access
create policy "Enable all access for all users" on public.products
for all using (true) with check (true);
