-- Create sales table
create table public.sales (
  id bigint generated by default as identity primary key,
  total numeric(10, 2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create sale_items table
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id),
  product_id bigint references public.products(id),
  quantity integer not null,
  price numeric(10, 2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

create policy "Enable all access for all users" on public.sales for all using (true) with check (true);
create policy "Enable all access for all users" on public.sale_items for all using (true) with check (true);

-- RPC Function to handle atomic Checkout
create or replace function checkout_cart(
  items jsonb
) returns bigint
language plpgsql
as $$
declare
  new_sale_id bigint;
  item jsonb;
  v_product_id bigint;
  v_quantity int;
  v_price numeric;
  v_total numeric := 0;
begin
  -- 1. Calculate Total
  for item in select * from jsonb_array_elements(items)
  loop
    v_product_id := (item->>'id')::bigint;
    v_quantity := (item->>'quantity')::int;
    v_price := (item->>'price')::numeric;
    v_total := v_total + (v_price * v_quantity);
  end loop;

  -- 2. Create Sale Record
  insert into public.sales (total)
  values (v_total)
  returning id into new_sale_id;

  -- 3. Process Items
  for item in select * from jsonb_array_elements(items)
  loop
    v_product_id := (item->>'id')::bigint;
    v_quantity := (item->>'quantity')::int;
    v_price := (item->>'price')::numeric;

    -- Insert sale item
    insert into public.sale_items (sale_id, product_id, quantity, price)
    values (new_sale_id, v_product_id, v_quantity, v_price);

    -- Decrement stock (Check if stock is sufficient could be added here)
    update public.products
    set stock = stock - v_quantity
    where id = v_product_id;
  end loop;

  return new_sale_id;
end;
$$;
